name: CI
on: [push, pull_request]
jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-python@v6
        with:
          python-version: '3.14'
          pip-install: -r requirements.txt

      - name: flake8 Lint
        uses: py-actions/flake8@v2

      - name: Set PYTHONPATH
        run: |
          echo "PYTHONPATH=$(PYTHONPATH):." >> $GITHUB_ENV

      - run: |
          coverage run -m pytest
          coverage lcov

      - uses: qltysh/qlty-action/coverage@v2
        with:
          token: ${{ secrets.QLTY_COVERAGE_TOKEN }}
          files: ./coverage.lcov
